@echo off

SETLOCAL

SET EXECUTABLE_NAME=main.exe

:: Debuging
SET DEBUG=TRUE
rem SET DEBUG=FALSE

:: Optimizations
 SET SPEED=SLOW
rem SET SPEED=MEDIUM
rem SET SPEED=FAST

ECHO %~dp0
SET BASE_DIR=%~dp0
SET SOURCE_DIR=%BASE_DIR%src
SET OUTPUT_DIR=.\build
SET OUTPUT=%EXECUTABLE_NAME%
SET INPUT=%SOURCE_DIR%\unity_build.c
SET CC=cl
SET INCLUDE_DIRS=/I %BASE_DIR%\src\toolbox /I %BASE_DIR%\src\coffee
SET WARNING_FLAGS=/Wall /wd4204 /wd4711 /wd5045 /wd4221 /wd4668 /wd4255 /wd4820 /wd4100 /wd4710 /wd4706 /wd4201 
SET CFLAGS=%INCLUDE_DIRS% %WARNING_FLAGS% /fp:fast /GS- /Zo -D_CRT_SECURE_NO_DEPRECATE  user32.lib gdi32.lib

IF "%DEBUG%"=="TRUE" (
	SET CFLAGS=%CFLAGS%  /Z7 -DTG_DEBUG
) ELSE (
	SET CFLAGS=%CFLAGS%
)

IF "%SPEED%"=="SLOW" (
	SET CFLAGS=%CFLAGS% /Od -DTG_SPEED_SLOW
) ELSE IF %SPEED%=="MEDIUM" (
	SET CFLAGS=%CFLAGS% /O1 -DTG_SPEED_MEDIUM
) ELSE (
	SET CFLAGS=%CFLAGS% /O2 -DTG_SPEED_FAST
)

if not exist %OUTPUT_DIR% mkdir %OUTPUT_DIR%

pushd %OUTPUT_DIR%

@echo on
%CC% %INPUT% %CFLAGS% /link /out:%OUTPUT%
@echo off
