#ifndef __ERROR_H
#define __ERROR_H 

typedef enum
{
    ERR_OK,
    ERR_OUT_OF_MEMORY, 
    ERR_ALLOCATORS_LINEAR_OUT_OF_MEMORY,
    ERR_ALLOCATORS_MEMORY_ALIGNMENT,
    ERR_PLATFORM_WEB_MEM_INIT,
    ERR_UNKNOWN,
    ERR_MATH_OVERFLOW,
    ERR_NOT_IMPLEMENTED
} ErrorCode;

#endif /* __ERROR_H */

